version: "3.7"

services:
  postgres:
    image: postgres:12.1
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5433:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

volumes:
  my_postgres_data:
